### ISSUE TITLE
Git organisation

### ISSUE THREAD

**Issue by Ldoppea** [SoftwareCraftsmanshipGrenoble/BrutalCodingConstraints#1]
Hi,

I'll try to upload our project this evening. Where is the best place to put the project? In a specific directory? Or in the root folder but in a different branch (like the one done by @ptaillard ) ?

**Comment by antechrestos** [comment]
@ldoppea I think we were saying to put it in a branch with the two developers name

**Comment by Ldoppea** [comment]
Ok merci 👍
